name: 'RaspberryPiPicoBuild'
description: 'Sets up action pipeline for building a Pico SDK project'

runs:
  using: "composite"
  steps:
    - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1.10.1
    - name: Checkout pico-sdk/2.1.1
      uses: actions/checkout@v4.1.1
      with:
        repository: raspberrypi/pico-sdk
        ref: 2.1.1
        path: pico-sdk
    - name: Checkout pico-sdk submodules
      working-directory: ${{github.workspace}}/pico-sdk
      run: git submodule update --init
      shell: bash
